--------------------------------------------------------
--  Ref Constraints for Table ASSOCIATE_SKILL
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."ASSOCIATE_SKILL" ADD CONSTRAINT "ASSOCIATE_SKILL_AID_FK" FOREIGN KEY ("ASSOCIATE_ID")
	  REFERENCES "SYSTEM"."ASSOCIATES" ("ASSOCIATEID") ENABLE;
  ALTER TABLE "SYSTEM"."ASSOCIATE_SKILL" ADD CONSTRAINT "ASSOCIATE_SKILL_SID_FK" FOREIGN KEY ("SKILL_ID")
	  REFERENCES "SYSTEM"."SKILL" ("SKILLID") ENABLE;
