--------------------------------------------------------
--  Ref Constraints for Table SKILL_REQUIRED_FOR_PROJECT
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."SKILL_REQUIRED_FOR_PROJECT" ADD CONSTRAINT "SKILL_REQUIRED_AID_FK" FOREIGN KEY ("SKILL_ID")
	  REFERENCES "SYSTEM"."SKILL" ("SKILLID") ENABLE;
  ALTER TABLE "SYSTEM"."SKILL_REQUIRED_FOR_PROJECT" ADD CONSTRAINT "SKILL_REQUIRED_PID_FK" FOREIGN KEY ("PROJECT_ID")
	  REFERENCES "SYSTEM"."PROJECTSS" ("PROJECTID") ENABLE;
