--------------------------------------------------------
--  Constraints for Table AQ$_QUEUES
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."AQ$_QUEUES" ADD CONSTRAINT "AQ$_QUEUES_CHECK" UNIQUE ("NAME", "TABLE_OBJNO") ENABLE;
  ALTER TABLE "SYSTEM"."AQ$_QUEUES" ADD CONSTRAINT "AQ$_QUEUES_PRIMARY" PRIMARY KEY ("OID") ENABLE;
  ALTER TABLE "SYSTEM"."AQ$_QUEUES" MODIFY ("ENABLE_FLAG" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."AQ$_QUEUES" MODIFY ("USAGE" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."AQ$_QUEUES" MODIFY ("TABLE_OBJNO" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."AQ$_QUEUES" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."AQ$_QUEUES" MODIFY ("EVENTID" NOT NULL ENABLE);
