--------------------------------------------------------
--  Constraints for Table AQ$_QUEUE_TABLES
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."AQ$_QUEUE_TABLES" ADD CONSTRAINT "AQ$_QUEUE_TABLES_PRIMARY" PRIMARY KEY ("OBJNO") ENABLE;
  ALTER TABLE "SYSTEM"."AQ$_QUEUE_TABLES" MODIFY ("SORT_COLS" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."AQ$_QUEUE_TABLES" MODIFY ("FLAGS" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."AQ$_QUEUE_TABLES" MODIFY ("OBJNO" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."AQ$_QUEUE_TABLES" MODIFY ("UDATA_TYPE" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."AQ$_QUEUE_TABLES" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."AQ$_QUEUE_TABLES" MODIFY ("SCHEMA" NOT NULL ENABLE);
