--------------------------------------------------------
--  Constraints for Table JOB_HISTORY
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."JOB_HISTORY" ADD CONSTRAINT "JHIST_EMP_ID_ST_DATE_PK" PRIMARY KEY ("EMPLOYEE_ID", "START_DATE") ENABLE;
  ALTER TABLE "SYSTEM"."JOB_HISTORY" ADD CONSTRAINT "JHIST_DATE_INTERVAL" CHECK (end_date > start_date) ENABLE;
  ALTER TABLE "SYSTEM"."JOB_HISTORY" MODIFY ("JOB_ID" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."JOB_HISTORY" MODIFY ("END_DATE" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."JOB_HISTORY" MODIFY ("START_DATE" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."JOB_HISTORY" MODIFY ("EMPLOYEE_ID" NOT NULL ENABLE);
