--------------------------------------------------------
--  File created - Thursday-September-28-2017   
--------------------------------------------------------
@D:\git\mylocalgitspace\e-learning\TYPES\REPCAT__OBJECT_NULL_VECTOR.sql
@D:\git\mylocalgitspace\e-learning\SEQUENCES\LOGMNR_EVOLVE_SEQ_.sql
@D:\git\mylocalgitspace\e-learning\SEQUENCES\LOGMNR_SEQ_.sql
@D:\git\mylocalgitspace\e-learning\SEQUENCES\LOGMNR_UIDS_.sql
@D:\git\mylocalgitspace\e-learning\SEQUENCES\MVIEW__ADVSEQ_GENERIC.sql
@D:\git\mylocalgitspace\e-learning\SEQUENCES\MVIEW__ADVSEQ_ID.sql
@D:\git\mylocalgitspace\e-learning\SEQUENCES\REPCAT__EXCEPTIONS_S.sql
@D:\git\mylocalgitspace\e-learning\SEQUENCES\REPCAT__FLAVORS_S.sql
@D:\git\mylocalgitspace\e-learning\SEQUENCES\REPCAT__FLAVOR_NAME_S.sql
@D:\git\mylocalgitspace\e-learning\SEQUENCES\REPCAT__REFRESH_TEMPLATES_S.sql
@D:\git\mylocalgitspace\e-learning\SEQUENCES\REPCAT__REPPROP_KEY.sql
@D:\git\mylocalgitspace\e-learning\SEQUENCES\REPCAT__RUNTIME_PARMS_S.sql
@D:\git\mylocalgitspace\e-learning\SEQUENCES\REPCAT__TEMPLATE_OBJECTS_S.sql
@D:\git\mylocalgitspace\e-learning\SEQUENCES\REPCAT__TEMPLATE_PARMS_S.sql
@D:\git\mylocalgitspace\e-learning\SEQUENCES\REPCAT__TEMPLATE_REFGROUPS_S.sql
@D:\git\mylocalgitspace\e-learning\SEQUENCES\REPCAT__TEMPLATE_SITES_S.sql
@D:\git\mylocalgitspace\e-learning\SEQUENCES\REPCAT__TEMP_OUTPUT_S.sql
@D:\git\mylocalgitspace\e-learning\SEQUENCES\REPCAT__USER_AUTHORIZATIONS_S.sql
@D:\git\mylocalgitspace\e-learning\SEQUENCES\REPCAT__USER_PARM_VALUES_S.sql
@D:\git\mylocalgitspace\e-learning\SEQUENCES\REPCAT_LOG_SEQUENCE.sql
@D:\git\mylocalgitspace\e-learning\SEQUENCES\TEMPLATE__TARGETS_S.sql
@D:\git\mylocalgitspace\e-learning\TABLES\AQ__INTERNET_AGENTS.sql
@D:\git\mylocalgitspace\e-learning\TABLES\AQ__INTERNET_AGENT_PRIVS.sql
@D:\git\mylocalgitspace\e-learning\TABLES\AQ__QUEUES.sql
@D:\git\mylocalgitspace\e-learning\TABLES\AQ__QUEUE_TABLES.sql
@D:\git\mylocalgitspace\e-learning\TABLES\AQ__SCHEDULES.sql
@D:\git\mylocalgitspace\e-learning\TABLES\ASSOCIATES.sql
@D:\git\mylocalgitspace\e-learning\TABLES\ASSOCIATE_ALLOCATION.sql
@D:\git\mylocalgitspace\e-learning\TABLES\ASSOCIATE_SKILL.sql
@D:\git\mylocalgitspace\e-learning\TABLES\COUNTRIES.sql
@D:\git\mylocalgitspace\e-learning\TABLES\DEF__CALLDEST.sql
@D:\git\mylocalgitspace\e-learning\TABLES\DEF__DEFAULTDEST.sql
@D:\git\mylocalgitspace\e-learning\TABLES\DEF__DESTINATION.sql
@D:\git\mylocalgitspace\e-learning\TABLES\DEF__ERROR.sql
@D:\git\mylocalgitspace\e-learning\TABLES\DEF__LOB.sql
@D:\git\mylocalgitspace\e-learning\TABLES\DEF__ORIGIN.sql
@D:\git\mylocalgitspace\e-learning\TABLES\DEF__PROPAGATOR.sql
@D:\git\mylocalgitspace\e-learning\TABLES\DEF__PUSHED_TRANSACTIONS.sql
@D:\git\mylocalgitspace\e-learning\TABLES\DEPARTMENTS.sql
@D:\git\mylocalgitspace\e-learning\TABLES\DEPT.sql
@D:\git\mylocalgitspace\e-learning\TABLES\EMP.sql
@D:\git\mylocalgitspace\e-learning\TABLES\EMPLOYEES.sql
@D:\git\mylocalgitspace\e-learning\TABLES\HELP.sql
@D:\git\mylocalgitspace\e-learning\TABLES\JOBS.sql
@D:\git\mylocalgitspace\e-learning\TABLES\JOB_HISTORY.sql
@D:\git\mylocalgitspace\e-learning\TABLES\LOCATIONS.sql
@D:\git\mylocalgitspace\e-learning\TABLES\LOGMNRC_DBNAME_UID_MAP.sql
@D:\git\mylocalgitspace\e-learning\TABLES\LOGMNRC_GSBA.sql
@D:\git\mylocalgitspace\e-learning\TABLES\LOGMNRC_GSII.sql
@D:\git\mylocalgitspace\e-learning\TABLES\LOGMNRC_GTCS.sql
@D:\git\mylocalgitspace\e-learning\TABLES\LOGMNRC_GTLO.sql
@D:\git\mylocalgitspace\e-learning\TABLES\LOGMNRP_CTAS_PART_MAP.sql
@D:\git\mylocalgitspace\e-learning\TABLES\LOGMNRT_MDDL_.sql
@D:\git\mylocalgitspace\e-learning\TABLES\LOGMNR_AGE_SPILL_.sql
@D:\git\mylocalgitspace\e-learning\TABLES\LOGMNR_ATTRCOL_.sql
@D:\git\mylocalgitspace\e-learning\TABLES\LOGMNR_ATTRIBUTE_.sql
@D:\git\mylocalgitspace\e-learning\TABLES\LOGMNR_CCOL_.sql
@D:\git\mylocalgitspace\e-learning\TABLES\LOGMNR_CDEF_.sql
@D:\git\mylocalgitspace\e-learning\TABLES\LOGMNR_COL_.sql
@D:\git\mylocalgitspace\e-learning\TABLES\LOGMNR_COLTYPE_.sql
@D:\git\mylocalgitspace\e-learning\TABLES\LOGMNR_DICTIONARY_.sql
@D:\git\mylocalgitspace\e-learning\TABLES\LOGMNR_DICTSTATE_.sql
@D:\git\mylocalgitspace\e-learning\TABLES\LOGMNR_ENC_.sql
@D:\git\mylocalgitspace\e-learning\TABLES\LOGMNR_ERROR_.sql
@D:\git\mylocalgitspace\e-learning\TABLES\LOGMNR_FILTER_.sql
@D:\git\mylocalgitspace\e-learning\TABLES\LOGMNR_GLOBAL_.sql
@D:\git\mylocalgitspace\e-learning\TABLES\LOGMNR_GT_TAB_INCLUDE_.sql
@D:\git\mylocalgitspace\e-learning\TABLES\LOGMNR_GT_USER_INCLUDE_.sql
@D:\git\mylocalgitspace\e-learning\TABLES\LOGMNR_GT_XID_INCLUDE_.sql
@D:\git\mylocalgitspace\e-learning\TABLES\LOGMNR_ICOL_.sql
@D:\git\mylocalgitspace\e-learning\TABLES\LOGMNR_IND_.sql
@D:\git\mylocalgitspace\e-learning\TABLES\LOGMNR_INDCOMPART_.sql
@D:\git\mylocalgitspace\e-learning\TABLES\LOGMNR_INDPART_.sql
@D:\git\mylocalgitspace\e-learning\TABLES\LOGMNR_INDSUBPART_.sql
@D:\git\mylocalgitspace\e-learning\TABLES\LOGMNR_INTEGRATED_SPILL_.sql
@D:\git\mylocalgitspace\e-learning\TABLES\LOGMNR_KOPM_.sql
@D:\git\mylocalgitspace\e-learning\TABLES\LOGMNR_LOB_.sql
@D:\git\mylocalgitspace\e-learning\TABLES\LOGMNR_LOBFRAG_.sql
@D:\git\mylocalgitspace\e-learning\TABLES\LOGMNR_LOG_.sql
@D:\git\mylocalgitspace\e-learning\TABLES\LOGMNR_LOGMNR_BUILDLOG.sql
@D:\git\mylocalgitspace\e-learning\TABLES\LOGMNR_NTAB_.sql
@D:\git\mylocalgitspace\e-learning\TABLES\LOGMNR_OBJ_.sql
@D:\git\mylocalgitspace\e-learning\TABLES\LOGMNR_OPQTYPE_.sql
@D:\git\mylocalgitspace\e-learning\TABLES\LOGMNR_PARAMETER_.sql
@D:\git\mylocalgitspace\e-learning\TABLES\LOGMNR_PARTOBJ_.sql
@D:\git\mylocalgitspace\e-learning\TABLES\LOGMNR_PROCESSED_LOG_.sql
@D:\git\mylocalgitspace\e-learning\TABLES\LOGMNR_PROPS_.sql
@D:\git\mylocalgitspace\e-learning\TABLES\LOGMNR_REFCON_.sql
@D:\git\mylocalgitspace\e-learning\TABLES\LOGMNR_RESTART_CKPT_.sql
@D:\git\mylocalgitspace\e-learning\TABLES\LOGMNR_RESTART_CKPT_TXINFO_.sql
@D:\git\mylocalgitspace\e-learning\TABLES\LOGMNR_SEED_.sql
@D:\git\mylocalgitspace\e-learning\TABLES\LOGMNR_SESSION_.sql
@D:\git\mylocalgitspace\e-learning\TABLES\LOGMNR_SESSION_ACTIONS_.sql
@D:\git\mylocalgitspace\e-learning\TABLES\LOGMNR_SESSION_EVOLVE_.sql
@D:\git\mylocalgitspace\e-learning\TABLES\LOGMNR_SPILL_.sql
@D:\git\mylocalgitspace\e-learning\TABLES\LOGMNR_SUBCOLTYPE_.sql
@D:\git\mylocalgitspace\e-learning\TABLES\LOGMNR_TAB_.sql
@D:\git\mylocalgitspace\e-learning\TABLES\LOGMNR_TABCOMPART_.sql
@D:\git\mylocalgitspace\e-learning\TABLES\LOGMNR_TABPART_.sql
@D:\git\mylocalgitspace\e-learning\TABLES\LOGMNR_TABSUBPART_.sql
@D:\git\mylocalgitspace\e-learning\TABLES\LOGMNR_TS_.sql
@D:\git\mylocalgitspace\e-learning\TABLES\LOGMNR_TYPE_.sql
@D:\git\mylocalgitspace\e-learning\TABLES\LOGMNR_UID_.sql
@D:\git\mylocalgitspace\e-learning\TABLES\LOGMNR_USER_.sql
@D:\git\mylocalgitspace\e-learning\TABLES\LOGSTDBY_APPLY_MILESTONE.sql
@D:\git\mylocalgitspace\e-learning\TABLES\LOGSTDBY_APPLY_PROGRESS.sql
@D:\git\mylocalgitspace\e-learning\TABLES\LOGSTDBY_EDS_TABLES.sql
@D:\git\mylocalgitspace\e-learning\TABLES\LOGSTDBY_EVENTS.sql
@D:\git\mylocalgitspace\e-learning\TABLES\LOGSTDBY_FLASHBACK_SCN.sql
@D:\git\mylocalgitspace\e-learning\TABLES\LOGSTDBY_HISTORY.sql
@D:\git\mylocalgitspace\e-learning\TABLES\LOGSTDBY_PARAMETERS.sql
@D:\git\mylocalgitspace\e-learning\TABLES\LOGSTDBY_PLSQL.sql
@D:\git\mylocalgitspace\e-learning\TABLES\LOGSTDBY_SCN.sql
@D:\git\mylocalgitspace\e-learning\TABLES\LOGSTDBY_SKIP.sql
@D:\git\mylocalgitspace\e-learning\TABLES\LOGSTDBY_SKIP_SUPPORT.sql
@D:\git\mylocalgitspace\e-learning\TABLES\LOGSTDBY_SKIP_TRANSACTION.sql
@D:\git\mylocalgitspace\e-learning\TABLES\MVIEW__ADV_AJG.sql
@D:\git\mylocalgitspace\e-learning\TABLES\MVIEW__ADV_BASETABLE.sql
@D:\git\mylocalgitspace\e-learning\TABLES\MVIEW__ADV_CLIQUE.sql
@D:\git\mylocalgitspace\e-learning\TABLES\MVIEW__ADV_ELIGIBLE.sql
@D:\git\mylocalgitspace\e-learning\TABLES\MVIEW__ADV_EXCEPTIONS.sql
@D:\git\mylocalgitspace\e-learning\TABLES\MVIEW__ADV_FILTER.sql
@D:\git\mylocalgitspace\e-learning\TABLES\MVIEW__ADV_FILTERINSTANCE.sql
@D:\git\mylocalgitspace\e-learning\TABLES\MVIEW__ADV_FJG.sql
@D:\git\mylocalgitspace\e-learning\TABLES\MVIEW__ADV_GC.sql
@D:\git\mylocalgitspace\e-learning\TABLES\MVIEW__ADV_INFO.sql
@D:\git\mylocalgitspace\e-learning\TABLES\MVIEW__ADV_JOURNAL.sql
@D:\git\mylocalgitspace\e-learning\TABLES\MVIEW__ADV_LEVEL.sql
@D:\git\mylocalgitspace\e-learning\TABLES\MVIEW__ADV_LOG.sql
@D:\git\mylocalgitspace\e-learning\TABLES\MVIEW__ADV_OUTPUT.sql
@D:\git\mylocalgitspace\e-learning\TABLES\MVIEW__ADV_PARAMETERS.sql
@D:\git\mylocalgitspace\e-learning\TABLES\MVIEW__ADV_PLAN.sql
@D:\git\mylocalgitspace\e-learning\TABLES\MVIEW__ADV_PRETTY.sql
@D:\git\mylocalgitspace\e-learning\TABLES\MVIEW__ADV_ROLLUP.sql
@D:\git\mylocalgitspace\e-learning\TABLES\MVIEW__ADV_SQLDEPEND.sql
@D:\git\mylocalgitspace\e-learning\TABLES\MVIEW__ADV_TEMP.sql
@D:\git\mylocalgitspace\e-learning\TABLES\MVIEW__ADV_WORKLOAD.sql
@D:\git\mylocalgitspace\e-learning\TABLES\OL_.sql
@D:\git\mylocalgitspace\e-learning\TABLES\OL_HINTS.sql
@D:\git\mylocalgitspace\e-learning\TABLES\OL_NODES.sql
@D:\git\mylocalgitspace\e-learning\TABLES\PROJECTSS.sql
@D:\git\mylocalgitspace\e-learning\TABLES\REGIONS.sql
@D:\git\mylocalgitspace\e-learning\TABLES\REPCAT__AUDIT_ATTRIBUTE.sql
@D:\git\mylocalgitspace\e-learning\TABLES\REPCAT__AUDIT_COLUMN.sql
@D:\git\mylocalgitspace\e-learning\TABLES\REPCAT__COLUMN_GROUP.sql
@D:\git\mylocalgitspace\e-learning\TABLES\REPCAT__CONFLICT.sql
@D:\git\mylocalgitspace\e-learning\TABLES\REPCAT__DDL.sql
@D:\git\mylocalgitspace\e-learning\TABLES\REPCAT__EXCEPTIONS.sql
@D:\git\mylocalgitspace\e-learning\TABLES\REPCAT__EXTENSION.sql
@D:\git\mylocalgitspace\e-learning\TABLES\REPCAT__FLAVORS.sql
@D:\git\mylocalgitspace\e-learning\TABLES\REPCAT__FLAVOR_OBJECTS.sql
@D:\git\mylocalgitspace\e-learning\TABLES\REPCAT__GENERATED.sql
@D:\git\mylocalgitspace\e-learning\TABLES\REPCAT__GROUPED_COLUMN.sql
@D:\git\mylocalgitspace\e-learning\TABLES\REPCAT__INSTANTIATION_DDL.sql
@D:\git\mylocalgitspace\e-learning\TABLES\REPCAT__KEY_COLUMNS.sql
@D:\git\mylocalgitspace\e-learning\TABLES\REPCAT__OBJECT_PARMS.sql
@D:\git\mylocalgitspace\e-learning\TABLES\REPCAT__OBJECT_TYPES.sql
@D:\git\mylocalgitspace\e-learning\TABLES\REPCAT__PARAMETER_COLUMN.sql
@D:\git\mylocalgitspace\e-learning\TABLES\REPCAT__PRIORITY.sql
@D:\git\mylocalgitspace\e-learning\TABLES\REPCAT__PRIORITY_GROUP.sql
@D:\git\mylocalgitspace\e-learning\TABLES\REPCAT__REFRESH_TEMPLATES.sql
@D:\git\mylocalgitspace\e-learning\TABLES\REPCAT__REPCAT.sql
@D:\git\mylocalgitspace\e-learning\TABLES\REPCAT__REPCATLOG.sql
@D:\git\mylocalgitspace\e-learning\TABLES\REPCAT__REPCOLUMN.sql
@D:\git\mylocalgitspace\e-learning\TABLES\REPCAT__REPGROUP_PRIVS.sql
@D:\git\mylocalgitspace\e-learning\TABLES\REPCAT__REPOBJECT.sql
@D:\git\mylocalgitspace\e-learning\TABLES\REPCAT__REPPROP.sql
@D:\git\mylocalgitspace\e-learning\TABLES\REPCAT__REPSCHEMA.sql
@D:\git\mylocalgitspace\e-learning\TABLES\REPCAT__RESOLUTION.sql
@D:\git\mylocalgitspace\e-learning\TABLES\REPCAT__RESOLUTION_METHOD.sql
@D:\git\mylocalgitspace\e-learning\TABLES\REPCAT__RESOLUTION_STATISTICS.sql
@D:\git\mylocalgitspace\e-learning\TABLES\REPCAT__RESOL_STATS_CONTROL.sql
@D:\git\mylocalgitspace\e-learning\TABLES\REPCAT__RUNTIME_PARMS.sql
@D:\git\mylocalgitspace\e-learning\TABLES\REPCAT__SITES_NEW.sql
@D:\git\mylocalgitspace\e-learning\TABLES\REPCAT__SITE_OBJECTS.sql
@D:\git\mylocalgitspace\e-learning\TABLES\REPCAT__SNAPGROUP.sql
@D:\git\mylocalgitspace\e-learning\TABLES\REPCAT__TEMPLATE_OBJECTS.sql
@D:\git\mylocalgitspace\e-learning\TABLES\REPCAT__TEMPLATE_PARMS.sql
@D:\git\mylocalgitspace\e-learning\TABLES\REPCAT__TEMPLATE_REFGROUPS.sql
@D:\git\mylocalgitspace\e-learning\TABLES\REPCAT__TEMPLATE_SITES.sql
@D:\git\mylocalgitspace\e-learning\TABLES\REPCAT__TEMPLATE_STATUS.sql
@D:\git\mylocalgitspace\e-learning\TABLES\REPCAT__TEMPLATE_TARGETS.sql
@D:\git\mylocalgitspace\e-learning\TABLES\REPCAT__TEMPLATE_TYPES.sql
@D:\git\mylocalgitspace\e-learning\TABLES\REPCAT__USER_AUTHORIZATIONS.sql
@D:\git\mylocalgitspace\e-learning\TABLES\REPCAT__USER_PARM_VALUES.sql
@D:\git\mylocalgitspace\e-learning\TABLES\SKILL.sql
@D:\git\mylocalgitspace\e-learning\TABLES\SKILL_REQUIRED_FOR_PROJECT.sql
@D:\git\mylocalgitspace\e-learning\TABLES\SQLPLUS_PRODUCT_PROFILE.sql
@D:\git\mylocalgitspace\e-learning\VIEWS\AQ_DEF__AQCALL.sql
@D:\git\mylocalgitspace\e-learning\VIEWS\AQ_DEF__AQERROR.sql
@D:\git\mylocalgitspace\e-learning\VIEWS\AQ__DEF__AQCALL_F.sql
@D:\git\mylocalgitspace\e-learning\VIEWS\AQ__DEF__AQERROR_F.sql
@D:\git\mylocalgitspace\e-learning\VIEWS\EMP_DETAILS_VIEW.sql
@D:\git\mylocalgitspace\e-learning\VIEWS\MVIEW_EVALUATIONS.sql
@D:\git\mylocalgitspace\e-learning\VIEWS\MVIEW_EXCEPTIONS.sql
@D:\git\mylocalgitspace\e-learning\VIEWS\MVIEW_FILTER.sql
@D:\git\mylocalgitspace\e-learning\VIEWS\MVIEW_FILTERINSTANCE.sql
@D:\git\mylocalgitspace\e-learning\VIEWS\MVIEW_LOG.sql
@D:\git\mylocalgitspace\e-learning\VIEWS\MVIEW_RECOMMENDATIONS.sql
@D:\git\mylocalgitspace\e-learning\VIEWS\MVIEW_WORKLOAD.sql
@D:\git\mylocalgitspace\e-learning\VIEWS\PRODUCT_PRIVS.sql
@D:\git\mylocalgitspace\e-learning\INDEXES\AQ__QUEUES_CHECK.sql
@D:\git\mylocalgitspace\e-learning\INDEXES\AQ__QUEUES_PRIMARY.sql
@D:\git\mylocalgitspace\e-learning\INDEXES\AQ__QUEUE_TABLES_PRIMARY.sql
@D:\git\mylocalgitspace\e-learning\INDEXES\AQ__SCHEDULES_CHECK.sql
@D:\git\mylocalgitspace\e-learning\INDEXES\AQ__SCHEDULES_PRIMARY.sql
@D:\git\mylocalgitspace\e-learning\INDEXES\ASSOCIATE_ALLOCATION_PK.sql
@D:\git\mylocalgitspace\e-learning\INDEXES\ASSOCIATE_SKILL_PK.sql
@D:\git\mylocalgitspace\e-learning\INDEXES\COUNTRY_C_ID_PK.sql
@D:\git\mylocalgitspace\e-learning\INDEXES\DEF__CALLDEST_N2.sql
@D:\git\mylocalgitspace\e-learning\INDEXES\DEF__CALLDEST_PRIMARY.sql
@D:\git\mylocalgitspace\e-learning\INDEXES\DEF__DEFAULTDEST_PRIMARY.sql
@D:\git\mylocalgitspace\e-learning\INDEXES\DEF__DESTINATION_PRIMARY.sql
@D:\git\mylocalgitspace\e-learning\INDEXES\DEF__ERROR_PRIMARY.sql
@D:\git\mylocalgitspace\e-learning\INDEXES\DEF__LOB_N1.sql
@D:\git\mylocalgitspace\e-learning\INDEXES\DEF__LOB_PRIMARY.sql
@D:\git\mylocalgitspace\e-learning\INDEXES\DEF__PROPAGATOR_PRIMARY.sql
@D:\git\mylocalgitspace\e-learning\INDEXES\DEF__PUSHED_TRAN_PRIMARY.sql
@D:\git\mylocalgitspace\e-learning\INDEXES\DEF__TRANORDER.sql
@D:\git\mylocalgitspace\e-learning\INDEXES\DEPT_ID_PK.sql
@D:\git\mylocalgitspace\e-learning\INDEXES\DEPT_LOCATION_IX.sql
@D:\git\mylocalgitspace\e-learning\INDEXES\EMP_DEPARTMENT_IX.sql
@D:\git\mylocalgitspace\e-learning\INDEXES\EMP_EMAIL_UK.sql
@D:\git\mylocalgitspace\e-learning\INDEXES\EMP_EMP_ID_PK.sql
@D:\git\mylocalgitspace\e-learning\INDEXES\EMP_JOB_IX.sql
@D:\git\mylocalgitspace\e-learning\INDEXES\EMP_MANAGER_IX.sql
@D:\git\mylocalgitspace\e-learning\INDEXES\EMP_NAME_IX.sql
@D:\git\mylocalgitspace\e-learning\INDEXES\HELP_TOPIC_SEQ.sql
@D:\git\mylocalgitspace\e-learning\INDEXES\I1_QUEUES.sql
@D:\git\mylocalgitspace\e-learning\INDEXES\I1_QUEUE_TABLES.sql
@D:\git\mylocalgitspace\e-learning\INDEXES\I_REPCAT__SNAPGROUP1.sql
@D:\git\mylocalgitspace\e-learning\INDEXES\JHIST_DEPARTMENT_IX.sql
@D:\git\mylocalgitspace\e-learning\INDEXES\JHIST_EMPLOYEE_IX.sql
@D:\git\mylocalgitspace\e-learning\INDEXES\JHIST_EMP_ID_ST_DATE_PK.sql
@D:\git\mylocalgitspace\e-learning\INDEXES\JHIST_JOB_IX.sql
@D:\git\mylocalgitspace\e-learning\INDEXES\JOB_ID_PK.sql
@D:\git\mylocalgitspace\e-learning\INDEXES\LOC_CITY_IX.sql
@D:\git\mylocalgitspace\e-learning\INDEXES\LOC_COUNTRY_IX.sql
@D:\git\mylocalgitspace\e-learning\INDEXES\LOC_ID_PK.sql
@D:\git\mylocalgitspace\e-learning\INDEXES\LOC_STATE_PROVINCE_IX.sql
@D:\git\mylocalgitspace\e-learning\INDEXES\LOGMNRC_DBNAME_UID_MAP_PK.sql
@D:\git\mylocalgitspace\e-learning\INDEXES\LOGMNRC_GSBA_PK.sql
@D:\git\mylocalgitspace\e-learning\INDEXES\LOGMNRC_GSII_PK.sql
@D:\git\mylocalgitspace\e-learning\INDEXES\LOGMNRC_GTCS_PK.sql
@D:\git\mylocalgitspace\e-learning\INDEXES\LOGMNRC_GTLO_PK.sql
@D:\git\mylocalgitspace\e-learning\INDEXES\LOGMNRC_I2GTCS.sql
@D:\git\mylocalgitspace\e-learning\INDEXES\LOGMNRC_I2GTLO.sql
@D:\git\mylocalgitspace\e-learning\INDEXES\LOGMNRC_I3GTLO.sql
@D:\git\mylocalgitspace\e-learning\INDEXES\LOGMNRP_CTAS_PART_MAP_I.sql
@D:\git\mylocalgitspace\e-learning\INDEXES\LOGMNRP_CTAS_PART_MAP_PK.sql
@D:\git\mylocalgitspace\e-learning\INDEXES\LOGMNRT_MDDL__PK.sql
@D:\git\mylocalgitspace\e-learning\INDEXES\LOGMNR_AGE_SPILL__PK.sql
@D:\git\mylocalgitspace\e-learning\INDEXES\LOGMNR_I1ATTRCOL_.sql
@D:\git\mylocalgitspace\e-learning\INDEXES\LOGMNR_I1ATTRIBUTE_.sql
@D:\git\mylocalgitspace\e-learning\INDEXES\LOGMNR_I1CCOL_.sql
@D:\git\mylocalgitspace\e-learning\INDEXES\LOGMNR_I1CDEF_.sql
@D:\git\mylocalgitspace\e-learning\INDEXES\LOGMNR_I1COL_.sql
@D:\git\mylocalgitspace\e-learning\INDEXES\LOGMNR_I1COLTYPE_.sql
@D:\git\mylocalgitspace\e-learning\INDEXES\LOGMNR_I1DICTIONARY_.sql
@D:\git\mylocalgitspace\e-learning\INDEXES\LOGMNR_I1ENC_.sql
@D:\git\mylocalgitspace\e-learning\INDEXES\LOGMNR_I1ICOL_.sql
@D:\git\mylocalgitspace\e-learning\INDEXES\LOGMNR_I1IND_.sql
@D:\git\mylocalgitspace\e-learning\INDEXES\LOGMNR_I1INDCOMPART_.sql
@D:\git\mylocalgitspace\e-learning\INDEXES\LOGMNR_I1INDPART_.sql
@D:\git\mylocalgitspace\e-learning\INDEXES\LOGMNR_I1INDSUBPART_.sql
@D:\git\mylocalgitspace\e-learning\INDEXES\LOGMNR_I1KOPM_.sql
@D:\git\mylocalgitspace\e-learning\INDEXES\LOGMNR_I1LOB_.sql
@D:\git\mylocalgitspace\e-learning\INDEXES\LOGMNR_I1LOBFRAG_.sql
@D:\git\mylocalgitspace\e-learning\INDEXES\LOGMNR_I1LOGMNR_BUILDLOG.sql
@D:\git\mylocalgitspace\e-learning\INDEXES\LOGMNR_I1NTAB_.sql
@D:\git\mylocalgitspace\e-learning\INDEXES\LOGMNR_I1OBJ_.sql
@D:\git\mylocalgitspace\e-learning\INDEXES\LOGMNR_I1OPQTYPE_.sql
@D:\git\mylocalgitspace\e-learning\INDEXES\LOGMNR_I1PARTOBJ_.sql
@D:\git\mylocalgitspace\e-learning\INDEXES\LOGMNR_I1PROPS_.sql
@D:\git\mylocalgitspace\e-learning\INDEXES\LOGMNR_I1REFCON_.sql
@D:\git\mylocalgitspace\e-learning\INDEXES\LOGMNR_I1SEED_.sql
@D:\git\mylocalgitspace\e-learning\INDEXES\LOGMNR_I1SUBCOLTYPE_.sql
@D:\git\mylocalgitspace\e-learning\INDEXES\LOGMNR_I1TAB_.sql
@D:\git\mylocalgitspace\e-learning\INDEXES\LOGMNR_I1TABCOMPART_.sql
@D:\git\mylocalgitspace\e-learning\INDEXES\LOGMNR_I1TABPART_.sql
@D:\git\mylocalgitspace\e-learning\INDEXES\LOGMNR_I1TABSUBPART_.sql
@D:\git\mylocalgitspace\e-learning\INDEXES\LOGMNR_I1TS_.sql
@D:\git\mylocalgitspace\e-learning\INDEXES\LOGMNR_I1TYPE_.sql
@D:\git\mylocalgitspace\e-learning\INDEXES\LOGMNR_I1USER_.sql
@D:\git\mylocalgitspace\e-learning\INDEXES\LOGMNR_I2COL_.sql
@D:\git\mylocalgitspace\e-learning\INDEXES\LOGMNR_I2IND_.sql
@D:\git\mylocalgitspace\e-learning\INDEXES\LOGMNR_I2INDPART_.sql
@D:\git\mylocalgitspace\e-learning\INDEXES\LOGMNR_I2NTAB_.sql
@D:\git\mylocalgitspace\e-learning\INDEXES\LOGMNR_I2OBJ_.sql
@D:\git\mylocalgitspace\e-learning\INDEXES\LOGMNR_I2SEED_.sql
@D:\git\mylocalgitspace\e-learning\INDEXES\LOGMNR_I2TAB_.sql
@D:\git\mylocalgitspace\e-learning\INDEXES\LOGMNR_I2TABCOMPART_.sql
@D:\git\mylocalgitspace\e-learning\INDEXES\LOGMNR_I2TABPART_.sql
@D:\git\mylocalgitspace\e-learning\INDEXES\LOGMNR_I2TABSUBPART_.sql
@D:\git\mylocalgitspace\e-learning\INDEXES\LOGMNR_I3COL_.sql
@D:\git\mylocalgitspace\e-learning\INDEXES\LOGMNR_INTEG_SPILL__PK.sql
@D:\git\mylocalgitspace\e-learning\INDEXES\LOGMNR_LOG__FIRST_CHANGE_.sql
@D:\git\mylocalgitspace\e-learning\INDEXES\LOGMNR_LOG__FLAGS.sql
@D:\git\mylocalgitspace\e-learning\INDEXES\LOGMNR_LOG__PK.sql
@D:\git\mylocalgitspace\e-learning\INDEXES\LOGMNR_LOG__RECID.sql
@D:\git\mylocalgitspace\e-learning\INDEXES\LOGMNR_PARAMETER_INDX.sql
@D:\git\mylocalgitspace\e-learning\INDEXES\LOGMNR_PROCESSED_LOG__PK.sql
@D:\git\mylocalgitspace\e-learning\INDEXES\LOGMNR_RESTART_CKPT__PK.sql
@D:\git\mylocalgitspace\e-learning\INDEXES\LOGMNR_RESTART_CKPT_TXINFO__PK.sql
@D:\git\mylocalgitspace\e-learning\INDEXES\LOGMNR_SESSION_ACTION__PK.sql
@D:\git\mylocalgitspace\e-learning\INDEXES\LOGMNR_SESSION_EVOLVE__PK.sql
@D:\git\mylocalgitspace\e-learning\INDEXES\LOGMNR_SESSION_PK.sql
@D:\git\mylocalgitspace\e-learning\INDEXES\LOGMNR_SESSION_UK1.sql
@D:\git\mylocalgitspace\e-learning\INDEXES\LOGMNR_SPILL__PK.sql
@D:\git\mylocalgitspace\e-learning\INDEXES\LOGMNR_UID__PK.sql
@D:\git\mylocalgitspace\e-learning\INDEXES\LOGSTDBY_EDS_TABLES_PKEY.sql
@D:\git\mylocalgitspace\e-learning\INDEXES\LOGSTDBY_EVENTS_IND.sql
@D:\git\mylocalgitspace\e-learning\INDEXES\LOGSTDBY_EVENTS_IND_SCN.sql
@D:\git\mylocalgitspace\e-learning\INDEXES\LOGSTDBY_EVENTS_IND_XID.sql
@D:\git\mylocalgitspace\e-learning\INDEXES\LOGSTDBY_SKIP_IDX1.sql
@D:\git\mylocalgitspace\e-learning\INDEXES\LOGSTDBY_SKIP_IDX2.sql
@D:\git\mylocalgitspace\e-learning\INDEXES\LOGSTDBY_SKIP_IND.sql
@D:\git\mylocalgitspace\e-learning\INDEXES\MVIEW__ADV_AJG_PK.sql
@D:\git\mylocalgitspace\e-learning\INDEXES\MVIEW__ADV_BASETABLE_IDX_01.sql
@D:\git\mylocalgitspace\e-learning\INDEXES\MVIEW__ADV_CLIQUE_PK.sql
@D:\git\mylocalgitspace\e-learning\INDEXES\MVIEW__ADV_ELIGIBLE_PK.sql
@D:\git\mylocalgitspace\e-learning\INDEXES\MVIEW__ADV_FILTER_PK.sql
@D:\git\mylocalgitspace\e-learning\INDEXES\MVIEW__ADV_FJG_PK.sql
@D:\git\mylocalgitspace\e-learning\INDEXES\MVIEW__ADV_GC_PK.sql
@D:\git\mylocalgitspace\e-learning\INDEXES\MVIEW__ADV_INFO_PK.sql
@D:\git\mylocalgitspace\e-learning\INDEXES\MVIEW__ADV_JOURNAL_PK.sql
@D:\git\mylocalgitspace\e-learning\INDEXES\MVIEW__ADV_LEVEL_PK.sql
@D:\git\mylocalgitspace\e-learning\INDEXES\MVIEW__ADV_LOG_PK.sql
@D:\git\mylocalgitspace\e-learning\INDEXES\MVIEW__ADV_OUTPUT_PK.sql
@D:\git\mylocalgitspace\e-learning\INDEXES\MVIEW__ADV_PARAMETERS_PK.sql
@D:\git\mylocalgitspace\e-learning\INDEXES\MVIEW__ADV_PRETTY_IDX_01.sql
@D:\git\mylocalgitspace\e-learning\INDEXES\MVIEW__ADV_ROLLUP_PK.sql
@D:\git\mylocalgitspace\e-learning\INDEXES\MVIEW__ADV_SQLDEPEND_IDX_01.sql
@D:\git\mylocalgitspace\e-learning\INDEXES\MVIEW__ADV_TEMP_IDX_01.sql
@D:\git\mylocalgitspace\e-learning\INDEXES\MVIEW__ADV_WORKLOAD_IDX_01.sql
@D:\git\mylocalgitspace\e-learning\INDEXES\MVIEW__ADV_WORKLOAD_PK.sql
@D:\git\mylocalgitspace\e-learning\INDEXES\OL_HNT_NUM.sql
@D:\git\mylocalgitspace\e-learning\INDEXES\OL_NAME.sql
@D:\git\mylocalgitspace\e-learning\INDEXES\OL_SIGNATURE.sql
@D:\git\mylocalgitspace\e-learning\INDEXES\REG_ID_PK.sql
@D:\git\mylocalgitspace\e-learning\INDEXES\REPCAT__AUDIT_ATTRIBUTE_PK.sql
@D:\git\mylocalgitspace\e-learning\INDEXES\REPCAT__AUDIT_COLUMN_F1_IDX.sql
@D:\git\mylocalgitspace\e-learning\INDEXES\REPCAT__AUDIT_COLUMN_F2_IDX.sql
@D:\git\mylocalgitspace\e-learning\INDEXES\REPCAT__AUDIT_COLUMN_PK.sql
@D:\git\mylocalgitspace\e-learning\INDEXES\REPCAT__COLUMN_GROUP_PK.sql
@D:\git\mylocalgitspace\e-learning\INDEXES\REPCAT__CONFLICT_PK.sql
@D:\git\mylocalgitspace\e-learning\INDEXES\REPCAT__DDL.sql
@D:\git\mylocalgitspace\e-learning\INDEXES\REPCAT__DDL_INDEX.sql
@D:\git\mylocalgitspace\e-learning\INDEXES\REPCAT__EXCEPTIONS_PK.sql
@D:\git\mylocalgitspace\e-learning\INDEXES\REPCAT__FLAVORS_FK1_IDX.sql
@D:\git\mylocalgitspace\e-learning\INDEXES\REPCAT__FLAVORS_FNAME.sql
@D:\git\mylocalgitspace\e-learning\INDEXES\REPCAT__FLAVORS_GNAME.sql
@D:\git\mylocalgitspace\e-learning\INDEXES\REPCAT__FLAVORS_UNQ1.sql
@D:\git\mylocalgitspace\e-learning\INDEXES\REPCAT__FLAVOR_OBJECTS_FG.sql
@D:\git\mylocalgitspace\e-learning\INDEXES\REPCAT__FLAVOR_OBJECTS_FK1_IDX.sql
@D:\git\mylocalgitspace\e-learning\INDEXES\REPCAT__FLAVOR_OBJECTS_FK2_IDX.sql
@D:\git\mylocalgitspace\e-learning\INDEXES\REPCAT__FLAVOR_OBJECTS_PK.sql
@D:\git\mylocalgitspace\e-learning\INDEXES\REPCAT__GENERATED_N1.sql
@D:\git\mylocalgitspace\e-learning\INDEXES\REPCAT__GROUPED_COLUMN_F1_IDX.sql
@D:\git\mylocalgitspace\e-learning\INDEXES\REPCAT__GROUPED_COLUMN_PK.sql
@D:\git\mylocalgitspace\e-learning\INDEXES\REPCAT__INSTANTIATION_DDL_PK.sql
@D:\git\mylocalgitspace\e-learning\INDEXES\REPCAT__KEY_COLUMNS_PRIMARY.sql
@D:\git\mylocalgitspace\e-learning\INDEXES\REPCAT__KEY_COLUMNS_PRNT_IDX.sql
@D:\git\mylocalgitspace\e-learning\INDEXES\REPCAT__OBJECT_PARMS_N2.sql
@D:\git\mylocalgitspace\e-learning\INDEXES\REPCAT__OBJECT_PARMS_PK.sql
@D:\git\mylocalgitspace\e-learning\INDEXES\REPCAT__OBJECT_TYPE_PK.sql
@D:\git\mylocalgitspace\e-learning\INDEXES\REPCAT__PARAMETER_COLUMN_F1_I.sql
@D:\git\mylocalgitspace\e-learning\INDEXES\REPCAT__PARAMETER_COLUMN_PK.sql
@D:\git\mylocalgitspace\e-learning\INDEXES\REPCAT__PRIORITY_F1_IDX.sql
@D:\git\mylocalgitspace\e-learning\INDEXES\REPCAT__PRIORITY_GROUP_PK.sql
@D:\git\mylocalgitspace\e-learning\INDEXES\REPCAT__PRIORITY_GROUP_U1.sql
@D:\git\mylocalgitspace\e-learning\INDEXES\REPCAT__PRIORITY_PK.sql
@D:\git\mylocalgitspace\e-learning\INDEXES\REPCAT__REFRESH_TEMPLATES_PK.sql
@D:\git\mylocalgitspace\e-learning\INDEXES\REPCAT__REFRESH_TEMPLATES_U1.sql
@D:\git\mylocalgitspace\e-learning\INDEXES\REPCAT__REPCATLOG_GNAME.sql
@D:\git\mylocalgitspace\e-learning\INDEXES\REPCAT__REPCATLOG_PRIMARY.sql
@D:\git\mylocalgitspace\e-learning\INDEXES\REPCAT__REPCAT_PRIMARY.sql
@D:\git\mylocalgitspace\e-learning\INDEXES\REPCAT__REPCOLUMN_FK_IDX.sql
@D:\git\mylocalgitspace\e-learning\INDEXES\REPCAT__REPCOLUMN_PK.sql
@D:\git\mylocalgitspace\e-learning\INDEXES\REPCAT__REPGEN_PRIMARY.sql
@D:\git\mylocalgitspace\e-learning\INDEXES\REPCAT__REPGEN_PRNT_IDX.sql
@D:\git\mylocalgitspace\e-learning\INDEXES\REPCAT__REPGROUP_PRIVS_FK_IDX.sql
@D:\git\mylocalgitspace\e-learning\INDEXES\REPCAT__REPGROUP_PRIVS_N1.sql
@D:\git\mylocalgitspace\e-learning\INDEXES\REPCAT__REPGROUP_PRIVS_UK.sql
@D:\git\mylocalgitspace\e-learning\INDEXES\REPCAT__REPOBJECT_GNAME.sql
@D:\git\mylocalgitspace\e-learning\INDEXES\REPCAT__REPOBJECT_PRIMARY.sql
@D:\git\mylocalgitspace\e-learning\INDEXES\REPCAT__REPOBJECT_PRNT_IDX.sql
@D:\git\mylocalgitspace\e-learning\INDEXES\REPCAT__REPPROP_DBLINK_HOW.sql
@D:\git\mylocalgitspace\e-learning\INDEXES\REPCAT__REPPROP_KEY_INDEX.sql
@D:\git\mylocalgitspace\e-learning\INDEXES\REPCAT__REPPROP_PRIMARY.sql
@D:\git\mylocalgitspace\e-learning\INDEXES\REPCAT__REPPROP_PRNT2_IDX.sql
@D:\git\mylocalgitspace\e-learning\INDEXES\REPCAT__REPPROP_PRNT_IDX.sql
@D:\git\mylocalgitspace\e-learning\INDEXES\REPCAT__REPSCHEMA_DEST_IDX.sql
@D:\git\mylocalgitspace\e-learning\INDEXES\REPCAT__REPSCHEMA_PRIMARY.sql
@D:\git\mylocalgitspace\e-learning\INDEXES\REPCAT__REPSCHEMA_PRNT_IDX.sql
@D:\git\mylocalgitspace\e-learning\INDEXES\REPCAT__RESOLUTION_F3_IDX.sql
@D:\git\mylocalgitspace\e-learning\INDEXES\REPCAT__RESOLUTION_IDX2.sql
@D:\git\mylocalgitspace\e-learning\INDEXES\REPCAT__RESOLUTION_PK.sql
@D:\git\mylocalgitspace\e-learning\INDEXES\REPCAT__RESOLUTION_STATS_N1.sql
@D:\git\mylocalgitspace\e-learning\INDEXES\REPCAT__RESOL_METHOD_PK.sql
@D:\git\mylocalgitspace\e-learning\INDEXES\REPCAT__RESOL_STATS_CTRL_PK.sql
@D:\git\mylocalgitspace\e-learning\INDEXES\REPCAT__RUNTIME_PARMS_PK.sql
@D:\git\mylocalgitspace\e-learning\INDEXES\REPCAT__SITES_NEW_FK1_IDX.sql
@D:\git\mylocalgitspace\e-learning\INDEXES\REPCAT__SITES_NEW_FK2_IDX.sql
@D:\git\mylocalgitspace\e-learning\INDEXES\REPCAT__SITES_NEW_PK.sql
@D:\git\mylocalgitspace\e-learning\INDEXES\REPCAT__SITE_OBJECTS_N1.sql
@D:\git\mylocalgitspace\e-learning\INDEXES\REPCAT__SITE_OBJECTS_U1.sql
@D:\git\mylocalgitspace\e-learning\INDEXES\REPCAT__TEMPLATE_OBJECTS_N1.sql
@D:\git\mylocalgitspace\e-learning\INDEXES\REPCAT__TEMPLATE_OBJECTS_N2.sql
@D:\git\mylocalgitspace\e-learning\INDEXES\REPCAT__TEMPLATE_OBJECTS_PK.sql
@D:\git\mylocalgitspace\e-learning\INDEXES\REPCAT__TEMPLATE_OBJECTS_U1.sql
@D:\git\mylocalgitspace\e-learning\INDEXES\REPCAT__TEMPLATE_PARMS_PK.sql
@D:\git\mylocalgitspace\e-learning\INDEXES\REPCAT__TEMPLATE_PARMS_U1.sql
@D:\git\mylocalgitspace\e-learning\INDEXES\REPCAT__TEMPLATE_REFGROUPS_N1.sql
@D:\git\mylocalgitspace\e-learning\INDEXES\REPCAT__TEMPLATE_REFGROUPS_N2.sql
@D:\git\mylocalgitspace\e-learning\INDEXES\REPCAT__TEMPLATE_REFGROUPS_PK.sql
@D:\git\mylocalgitspace\e-learning\INDEXES\REPCAT__TEMPLATE_SITES_PK.sql
@D:\git\mylocalgitspace\e-learning\INDEXES\REPCAT__TEMPLATE_SITES_U1.sql
@D:\git\mylocalgitspace\e-learning\INDEXES\REPCAT__TEMPLATE_STATUS_PK.sql
@D:\git\mylocalgitspace\e-learning\INDEXES\REPCAT__TEMPLATE_TARGETS_U1.sql
@D:\git\mylocalgitspace\e-learning\INDEXES\REPCAT__TEMPLATE_TYPES_PK.sql
@D:\git\mylocalgitspace\e-learning\INDEXES\REPCAT__USER_AUTHORIZATIONS_N1.sql
@D:\git\mylocalgitspace\e-learning\INDEXES\REPCAT__USER_AUTHORIZATIONS_PK.sql
@D:\git\mylocalgitspace\e-learning\INDEXES\REPCAT__USER_AUTHORIZATIONS_U1.sql
@D:\git\mylocalgitspace\e-learning\INDEXES\REPCAT__USER_PARM_VALUES_PK.sql
@D:\git\mylocalgitspace\e-learning\INDEXES\REPCAT__USER_PARM_VALUES_U1.sql
@D:\git\mylocalgitspace\e-learning\INDEXES\SKILL_PROJECT_PK.sql
@D:\git\mylocalgitspace\e-learning\INDEXES\SYS_C001694.sql
@D:\git\mylocalgitspace\e-learning\INDEXES\SYS_C003081.sql
@D:\git\mylocalgitspace\e-learning\INDEXES\SYS_C003346.sql
@D:\git\mylocalgitspace\e-learning\INDEXES\SYS_C003540.sql
@D:\git\mylocalgitspace\e-learning\INDEXES\SYS_C003543.sql
@D:\git\mylocalgitspace\e-learning\INDEXES\SYS_C007036.sql
@D:\git\mylocalgitspace\e-learning\INDEXES\SYS_C007037.sql
@D:\git\mylocalgitspace\e-learning\INDEXES\SYS_C007041.sql
@D:\git\mylocalgitspace\e-learning\INDEXES\TEMPLATE__TARGETS_PK.sql
@D:\git\mylocalgitspace\e-learning\INDEXES\UNQ_PAIRS.sql
@D:\git\mylocalgitspace\e-learning\CONSTRAINTS\AQ__INTERNET_AGENTS.sql
@D:\git\mylocalgitspace\e-learning\CONSTRAINTS\AQ__INTERNET_AGENT_PRIVS.sql
@D:\git\mylocalgitspace\e-learning\CONSTRAINTS\AQ__QUEUES.sql
@D:\git\mylocalgitspace\e-learning\CONSTRAINTS\AQ__QUEUE_TABLES.sql
@D:\git\mylocalgitspace\e-learning\CONSTRAINTS\AQ__SCHEDULES.sql
@D:\git\mylocalgitspace\e-learning\CONSTRAINTS\ASSOCIATES.sql
@D:\git\mylocalgitspace\e-learning\CONSTRAINTS\ASSOCIATE_ALLOCATION.sql
@D:\git\mylocalgitspace\e-learning\CONSTRAINTS\ASSOCIATE_SKILL.sql
@D:\git\mylocalgitspace\e-learning\CONSTRAINTS\COUNTRIES.sql
@D:\git\mylocalgitspace\e-learning\CONSTRAINTS\DEF__CALLDEST.sql
@D:\git\mylocalgitspace\e-learning\CONSTRAINTS\DEF__DEFAULTDEST.sql
@D:\git\mylocalgitspace\e-learning\CONSTRAINTS\DEF__DESTINATION.sql
@D:\git\mylocalgitspace\e-learning\CONSTRAINTS\DEF__ERROR.sql
@D:\git\mylocalgitspace\e-learning\CONSTRAINTS\DEF__LOB.sql
@D:\git\mylocalgitspace\e-learning\CONSTRAINTS\DEF__PROPAGATOR.sql
@D:\git\mylocalgitspace\e-learning\CONSTRAINTS\DEF__PUSHED_TRANSACTIONS.sql
@D:\git\mylocalgitspace\e-learning\CONSTRAINTS\DEPARTMENTS.sql
@D:\git\mylocalgitspace\e-learning\CONSTRAINTS\EMPLOYEES.sql
@D:\git\mylocalgitspace\e-learning\CONSTRAINTS\HELP.sql
@D:\git\mylocalgitspace\e-learning\CONSTRAINTS\JOBS.sql
@D:\git\mylocalgitspace\e-learning\CONSTRAINTS\JOB_HISTORY.sql
@D:\git\mylocalgitspace\e-learning\CONSTRAINTS\LOCATIONS.sql
@D:\git\mylocalgitspace\e-learning\CONSTRAINTS\LOGMNRC_DBNAME_UID_MAP.sql
@D:\git\mylocalgitspace\e-learning\CONSTRAINTS\LOGMNRC_GSBA.sql
@D:\git\mylocalgitspace\e-learning\CONSTRAINTS\LOGMNRC_GSII.sql
@D:\git\mylocalgitspace\e-learning\CONSTRAINTS\LOGMNRC_GTCS.sql
@D:\git\mylocalgitspace\e-learning\CONSTRAINTS\LOGMNRC_GTLO.sql
@D:\git\mylocalgitspace\e-learning\CONSTRAINTS\LOGMNRP_CTAS_PART_MAP.sql
@D:\git\mylocalgitspace\e-learning\CONSTRAINTS\LOGMNRT_MDDL_.sql
@D:\git\mylocalgitspace\e-learning\CONSTRAINTS\LOGMNR_AGE_SPILL_.sql
@D:\git\mylocalgitspace\e-learning\CONSTRAINTS\LOGMNR_ATTRCOL_.sql
@D:\git\mylocalgitspace\e-learning\CONSTRAINTS\LOGMNR_ATTRIBUTE_.sql
@D:\git\mylocalgitspace\e-learning\CONSTRAINTS\LOGMNR_CCOL_.sql
@D:\git\mylocalgitspace\e-learning\CONSTRAINTS\LOGMNR_CDEF_.sql
@D:\git\mylocalgitspace\e-learning\CONSTRAINTS\LOGMNR_COL_.sql
@D:\git\mylocalgitspace\e-learning\CONSTRAINTS\LOGMNR_COLTYPE_.sql
@D:\git\mylocalgitspace\e-learning\CONSTRAINTS\LOGMNR_DICTIONARY_.sql
@D:\git\mylocalgitspace\e-learning\CONSTRAINTS\LOGMNR_DICTSTATE_.sql
@D:\git\mylocalgitspace\e-learning\CONSTRAINTS\LOGMNR_ENC_.sql
@D:\git\mylocalgitspace\e-learning\CONSTRAINTS\LOGMNR_ICOL_.sql
@D:\git\mylocalgitspace\e-learning\CONSTRAINTS\LOGMNR_IND_.sql
@D:\git\mylocalgitspace\e-learning\CONSTRAINTS\LOGMNR_INDCOMPART_.sql
@D:\git\mylocalgitspace\e-learning\CONSTRAINTS\LOGMNR_INDPART_.sql
@D:\git\mylocalgitspace\e-learning\CONSTRAINTS\LOGMNR_INDSUBPART_.sql
@D:\git\mylocalgitspace\e-learning\CONSTRAINTS\LOGMNR_INTEGRATED_SPILL_.sql
@D:\git\mylocalgitspace\e-learning\CONSTRAINTS\LOGMNR_KOPM_.sql
@D:\git\mylocalgitspace\e-learning\CONSTRAINTS\LOGMNR_LOB_.sql
@D:\git\mylocalgitspace\e-learning\CONSTRAINTS\LOGMNR_LOBFRAG_.sql
@D:\git\mylocalgitspace\e-learning\CONSTRAINTS\LOGMNR_LOG_.sql
@D:\git\mylocalgitspace\e-learning\CONSTRAINTS\LOGMNR_LOGMNR_BUILDLOG.sql
@D:\git\mylocalgitspace\e-learning\CONSTRAINTS\LOGMNR_NTAB_.sql
@D:\git\mylocalgitspace\e-learning\CONSTRAINTS\LOGMNR_OBJ_.sql
@D:\git\mylocalgitspace\e-learning\CONSTRAINTS\LOGMNR_OPQTYPE_.sql
@D:\git\mylocalgitspace\e-learning\CONSTRAINTS\LOGMNR_PARAMETER_.sql
@D:\git\mylocalgitspace\e-learning\CONSTRAINTS\LOGMNR_PARTOBJ_.sql
@D:\git\mylocalgitspace\e-learning\CONSTRAINTS\LOGMNR_PROCESSED_LOG_.sql
@D:\git\mylocalgitspace\e-learning\CONSTRAINTS\LOGMNR_PROPS_.sql
@D:\git\mylocalgitspace\e-learning\CONSTRAINTS\LOGMNR_REFCON_.sql
@D:\git\mylocalgitspace\e-learning\CONSTRAINTS\LOGMNR_RESTART_CKPT_.sql
@D:\git\mylocalgitspace\e-learning\CONSTRAINTS\LOGMNR_RESTART_CKPT_TXINFO_.sql
@D:\git\mylocalgitspace\e-learning\CONSTRAINTS\LOGMNR_SEED_.sql
@D:\git\mylocalgitspace\e-learning\CONSTRAINTS\LOGMNR_SESSION_.sql
@D:\git\mylocalgitspace\e-learning\CONSTRAINTS\LOGMNR_SESSION_ACTIONS_.sql
@D:\git\mylocalgitspace\e-learning\CONSTRAINTS\LOGMNR_SESSION_EVOLVE_.sql
@D:\git\mylocalgitspace\e-learning\CONSTRAINTS\LOGMNR_SPILL_.sql
@D:\git\mylocalgitspace\e-learning\CONSTRAINTS\LOGMNR_SUBCOLTYPE_.sql
@D:\git\mylocalgitspace\e-learning\CONSTRAINTS\LOGMNR_TAB_.sql
@D:\git\mylocalgitspace\e-learning\CONSTRAINTS\LOGMNR_TABCOMPART_.sql
@D:\git\mylocalgitspace\e-learning\CONSTRAINTS\LOGMNR_TABPART_.sql
@D:\git\mylocalgitspace\e-learning\CONSTRAINTS\LOGMNR_TABSUBPART_.sql
@D:\git\mylocalgitspace\e-learning\CONSTRAINTS\LOGMNR_TS_.sql
@D:\git\mylocalgitspace\e-learning\CONSTRAINTS\LOGMNR_TYPE_.sql
@D:\git\mylocalgitspace\e-learning\CONSTRAINTS\LOGMNR_UID_.sql
@D:\git\mylocalgitspace\e-learning\CONSTRAINTS\LOGMNR_USER_.sql
@D:\git\mylocalgitspace\e-learning\CONSTRAINTS\LOGSTDBY_APPLY_MILESTONE.sql
@D:\git\mylocalgitspace\e-learning\CONSTRAINTS\LOGSTDBY_EDS_TABLES.sql
@D:\git\mylocalgitspace\e-learning\CONSTRAINTS\LOGSTDBY_EVENTS.sql
@D:\git\mylocalgitspace\e-learning\CONSTRAINTS\LOGSTDBY_FLASHBACK_SCN.sql
@D:\git\mylocalgitspace\e-learning\CONSTRAINTS\LOGSTDBY_SKIP_SUPPORT.sql
@D:\git\mylocalgitspace\e-learning\CONSTRAINTS\MVIEW__ADV_AJG.sql
@D:\git\mylocalgitspace\e-learning\CONSTRAINTS\MVIEW__ADV_BASETABLE.sql
@D:\git\mylocalgitspace\e-learning\CONSTRAINTS\MVIEW__ADV_CLIQUE.sql
@D:\git\mylocalgitspace\e-learning\CONSTRAINTS\MVIEW__ADV_ELIGIBLE.sql
@D:\git\mylocalgitspace\e-learning\CONSTRAINTS\MVIEW__ADV_FILTER.sql
@D:\git\mylocalgitspace\e-learning\CONSTRAINTS\MVIEW__ADV_FILTERINSTANCE.sql
@D:\git\mylocalgitspace\e-learning\CONSTRAINTS\MVIEW__ADV_FJG.sql
@D:\git\mylocalgitspace\e-learning\CONSTRAINTS\MVIEW__ADV_GC.sql
@D:\git\mylocalgitspace\e-learning\CONSTRAINTS\MVIEW__ADV_INFO.sql
@D:\git\mylocalgitspace\e-learning\CONSTRAINTS\MVIEW__ADV_JOURNAL.sql
@D:\git\mylocalgitspace\e-learning\CONSTRAINTS\MVIEW__ADV_LEVEL.sql
@D:\git\mylocalgitspace\e-learning\CONSTRAINTS\MVIEW__ADV_LOG.sql
@D:\git\mylocalgitspace\e-learning\CONSTRAINTS\MVIEW__ADV_OUTPUT.sql
@D:\git\mylocalgitspace\e-learning\CONSTRAINTS\MVIEW__ADV_PARAMETERS.sql
@D:\git\mylocalgitspace\e-learning\CONSTRAINTS\MVIEW__ADV_ROLLUP.sql
@D:\git\mylocalgitspace\e-learning\CONSTRAINTS\MVIEW__ADV_WORKLOAD.sql
@D:\git\mylocalgitspace\e-learning\CONSTRAINTS\PROJECTSS.sql
@D:\git\mylocalgitspace\e-learning\CONSTRAINTS\REGIONS.sql
@D:\git\mylocalgitspace\e-learning\CONSTRAINTS\REPCAT__AUDIT_ATTRIBUTE.sql
@D:\git\mylocalgitspace\e-learning\CONSTRAINTS\REPCAT__AUDIT_COLUMN.sql
@D:\git\mylocalgitspace\e-learning\CONSTRAINTS\REPCAT__COLUMN_GROUP.sql
@D:\git\mylocalgitspace\e-learning\CONSTRAINTS\REPCAT__CONFLICT.sql
@D:\git\mylocalgitspace\e-learning\CONSTRAINTS\REPCAT__EXCEPTIONS.sql
@D:\git\mylocalgitspace\e-learning\CONSTRAINTS\REPCAT__EXTENSION.sql
@D:\git\mylocalgitspace\e-learning\CONSTRAINTS\REPCAT__FLAVORS.sql
@D:\git\mylocalgitspace\e-learning\CONSTRAINTS\REPCAT__FLAVOR_OBJECTS.sql
@D:\git\mylocalgitspace\e-learning\CONSTRAINTS\REPCAT__GENERATED.sql
@D:\git\mylocalgitspace\e-learning\CONSTRAINTS\REPCAT__GROUPED_COLUMN.sql
@D:\git\mylocalgitspace\e-learning\CONSTRAINTS\REPCAT__INSTANTIATION_DDL.sql
@D:\git\mylocalgitspace\e-learning\CONSTRAINTS\REPCAT__KEY_COLUMNS.sql
@D:\git\mylocalgitspace\e-learning\CONSTRAINTS\REPCAT__OBJECT_PARMS.sql
@D:\git\mylocalgitspace\e-learning\CONSTRAINTS\REPCAT__OBJECT_TYPES.sql
@D:\git\mylocalgitspace\e-learning\CONSTRAINTS\REPCAT__PARAMETER_COLUMN.sql
@D:\git\mylocalgitspace\e-learning\CONSTRAINTS\REPCAT__PRIORITY.sql
@D:\git\mylocalgitspace\e-learning\CONSTRAINTS\REPCAT__PRIORITY_GROUP.sql
@D:\git\mylocalgitspace\e-learning\CONSTRAINTS\REPCAT__REFRESH_TEMPLATES.sql
@D:\git\mylocalgitspace\e-learning\CONSTRAINTS\REPCAT__REPCAT.sql
@D:\git\mylocalgitspace\e-learning\CONSTRAINTS\REPCAT__REPCATLOG.sql
@D:\git\mylocalgitspace\e-learning\CONSTRAINTS\REPCAT__REPCOLUMN.sql
@D:\git\mylocalgitspace\e-learning\CONSTRAINTS\REPCAT__REPGROUP_PRIVS.sql
@D:\git\mylocalgitspace\e-learning\CONSTRAINTS\REPCAT__REPOBJECT.sql
@D:\git\mylocalgitspace\e-learning\CONSTRAINTS\REPCAT__REPPROP.sql
@D:\git\mylocalgitspace\e-learning\CONSTRAINTS\REPCAT__REPSCHEMA.sql
@D:\git\mylocalgitspace\e-learning\CONSTRAINTS\REPCAT__RESOLUTION.sql
@D:\git\mylocalgitspace\e-learning\CONSTRAINTS\REPCAT__RESOLUTION_METHOD.sql
@D:\git\mylocalgitspace\e-learning\CONSTRAINTS\REPCAT__RESOLUTION_STATISTICS.sql
@D:\git\mylocalgitspace\e-learning\CONSTRAINTS\REPCAT__RESOL_STATS_CONTROL.sql
@D:\git\mylocalgitspace\e-learning\CONSTRAINTS\REPCAT__SITES_NEW.sql
@D:\git\mylocalgitspace\e-learning\CONSTRAINTS\REPCAT__SITE_OBJECTS.sql
@D:\git\mylocalgitspace\e-learning\CONSTRAINTS\REPCAT__TEMPLATE_OBJECTS.sql
@D:\git\mylocalgitspace\e-learning\CONSTRAINTS\REPCAT__TEMPLATE_PARMS.sql
@D:\git\mylocalgitspace\e-learning\CONSTRAINTS\REPCAT__TEMPLATE_REFGROUPS.sql
@D:\git\mylocalgitspace\e-learning\CONSTRAINTS\REPCAT__TEMPLATE_SITES.sql
@D:\git\mylocalgitspace\e-learning\CONSTRAINTS\REPCAT__TEMPLATE_STATUS.sql
@D:\git\mylocalgitspace\e-learning\CONSTRAINTS\REPCAT__TEMPLATE_TARGETS.sql
@D:\git\mylocalgitspace\e-learning\CONSTRAINTS\REPCAT__TEMPLATE_TYPES.sql
@D:\git\mylocalgitspace\e-learning\CONSTRAINTS\REPCAT__USER_AUTHORIZATIONS.sql
@D:\git\mylocalgitspace\e-learning\CONSTRAINTS\REPCAT__USER_PARM_VALUES.sql
@D:\git\mylocalgitspace\e-learning\CONSTRAINTS\SKILL.sql
@D:\git\mylocalgitspace\e-learning\CONSTRAINTS\SKILL_REQUIRED_FOR_PROJECT.sql
@D:\git\mylocalgitspace\e-learning\CONSTRAINTS\SQLPLUS_PRODUCT_PROFILE.sql
@D:\git\mylocalgitspace\e-learning\REF_CONSTRAINTS\AQ__INTERNET_AGENT_PRIVS.sql
@D:\git\mylocalgitspace\e-learning\REF_CONSTRAINTS\ASSOCIATE_ALLOCATION.sql
@D:\git\mylocalgitspace\e-learning\REF_CONSTRAINTS\ASSOCIATE_SKILL.sql
@D:\git\mylocalgitspace\e-learning\REF_CONSTRAINTS\COUNTRIES.sql
@D:\git\mylocalgitspace\e-learning\REF_CONSTRAINTS\DEF__CALLDEST.sql
@D:\git\mylocalgitspace\e-learning\REF_CONSTRAINTS\DEPARTMENTS.sql
@D:\git\mylocalgitspace\e-learning\REF_CONSTRAINTS\EMPLOYEES.sql
@D:\git\mylocalgitspace\e-learning\REF_CONSTRAINTS\JOB_HISTORY.sql
@D:\git\mylocalgitspace\e-learning\REF_CONSTRAINTS\LOCATIONS.sql
@D:\git\mylocalgitspace\e-learning\REF_CONSTRAINTS\MVIEW__ADV_AJG.sql
@D:\git\mylocalgitspace\e-learning\REF_CONSTRAINTS\MVIEW__ADV_BASETABLE.sql
@D:\git\mylocalgitspace\e-learning\REF_CONSTRAINTS\MVIEW__ADV_CLIQUE.sql
@D:\git\mylocalgitspace\e-learning\REF_CONSTRAINTS\MVIEW__ADV_ELIGIBLE.sql
@D:\git\mylocalgitspace\e-learning\REF_CONSTRAINTS\MVIEW__ADV_EXCEPTIONS.sql
@D:\git\mylocalgitspace\e-learning\REF_CONSTRAINTS\MVIEW__ADV_FILTERINSTANCE.sql
@D:\git\mylocalgitspace\e-learning\REF_CONSTRAINTS\MVIEW__ADV_FJG.sql
@D:\git\mylocalgitspace\e-learning\REF_CONSTRAINTS\MVIEW__ADV_GC.sql
@D:\git\mylocalgitspace\e-learning\REF_CONSTRAINTS\MVIEW__ADV_INFO.sql
@D:\git\mylocalgitspace\e-learning\REF_CONSTRAINTS\MVIEW__ADV_JOURNAL.sql
@D:\git\mylocalgitspace\e-learning\REF_CONSTRAINTS\MVIEW__ADV_LEVEL.sql
@D:\git\mylocalgitspace\e-learning\REF_CONSTRAINTS\MVIEW__ADV_OUTPUT.sql
@D:\git\mylocalgitspace\e-learning\REF_CONSTRAINTS\MVIEW__ADV_ROLLUP.sql
@D:\git\mylocalgitspace\e-learning\REF_CONSTRAINTS\REPCAT__AUDIT_COLUMN.sql
@D:\git\mylocalgitspace\e-learning\REF_CONSTRAINTS\REPCAT__DDL.sql
@D:\git\mylocalgitspace\e-learning\REF_CONSTRAINTS\REPCAT__FLAVORS.sql
@D:\git\mylocalgitspace\e-learning\REF_CONSTRAINTS\REPCAT__FLAVOR_OBJECTS.sql
@D:\git\mylocalgitspace\e-learning\REF_CONSTRAINTS\REPCAT__GENERATED.sql
@D:\git\mylocalgitspace\e-learning\REF_CONSTRAINTS\REPCAT__GROUPED_COLUMN.sql
@D:\git\mylocalgitspace\e-learning\REF_CONSTRAINTS\REPCAT__INSTANTIATION_DDL.sql
@D:\git\mylocalgitspace\e-learning\REF_CONSTRAINTS\REPCAT__KEY_COLUMNS.sql
@D:\git\mylocalgitspace\e-learning\REF_CONSTRAINTS\REPCAT__OBJECT_PARMS.sql
@D:\git\mylocalgitspace\e-learning\REF_CONSTRAINTS\REPCAT__PARAMETER_COLUMN.sql
@D:\git\mylocalgitspace\e-learning\REF_CONSTRAINTS\REPCAT__PRIORITY.sql
@D:\git\mylocalgitspace\e-learning\REF_CONSTRAINTS\REPCAT__REFRESH_TEMPLATES.sql
@D:\git\mylocalgitspace\e-learning\REF_CONSTRAINTS\REPCAT__REPCOLUMN.sql
@D:\git\mylocalgitspace\e-learning\REF_CONSTRAINTS\REPCAT__REPGROUP_PRIVS.sql
@D:\git\mylocalgitspace\e-learning\REF_CONSTRAINTS\REPCAT__REPOBJECT.sql
@D:\git\mylocalgitspace\e-learning\REF_CONSTRAINTS\REPCAT__REPPROP.sql
@D:\git\mylocalgitspace\e-learning\REF_CONSTRAINTS\REPCAT__REPSCHEMA.sql
@D:\git\mylocalgitspace\e-learning\REF_CONSTRAINTS\REPCAT__RESOLUTION.sql
@D:\git\mylocalgitspace\e-learning\REF_CONSTRAINTS\REPCAT__SITES_NEW.sql
@D:\git\mylocalgitspace\e-learning\REF_CONSTRAINTS\REPCAT__SITE_OBJECTS.sql
@D:\git\mylocalgitspace\e-learning\REF_CONSTRAINTS\REPCAT__TEMPLATE_OBJECTS.sql
@D:\git\mylocalgitspace\e-learning\REF_CONSTRAINTS\REPCAT__TEMPLATE_PARMS.sql
@D:\git\mylocalgitspace\e-learning\REF_CONSTRAINTS\REPCAT__TEMPLATE_REFGROUPS.sql
@D:\git\mylocalgitspace\e-learning\REF_CONSTRAINTS\REPCAT__USER_AUTHORIZATIONS.sql
@D:\git\mylocalgitspace\e-learning\REF_CONSTRAINTS\REPCAT__USER_PARM_VALUES.sql
@D:\git\mylocalgitspace\e-learning\REF_CONSTRAINTS\SKILL_REQUIRED_FOR_PROJECT.sql
@D:\git\mylocalgitspace\e-learning\TRIGGERS\DEF__PROPAGATOR_TRIG.sql
@D:\git\mylocalgitspace\e-learning\TRIGGERS\REPCATLOGTRIG.sql
@D:\git\mylocalgitspace\e-learning\PACKAGES\DBMS_REPCAT_AUTH.sql
@D:\git\mylocalgitspace\e-learning\PACKAGES\PKG_HAPPY.sql
@D:\git\mylocalgitspace\e-learning\PACKAGES\PKG_HELLO.sql
@D:\git\mylocalgitspace\e-learning\PACKAGE_BODIES\DBMS_REPCAT_AUTH.sql
@D:\git\mylocalgitspace\e-learning\PACKAGE_BODIES\PKG_HAPPY.sql
@D:\git\mylocalgitspace\e-learning\PACKAGE_BODIES\PKG_HELLO.sql
@D:\git\mylocalgitspace\e-learning\PROCEDURES\ORA__SYS_REP_AUTH.sql
@D:\git\mylocalgitspace\e-learning\PROCEDURES\PRINT_HAPPY.sql
@D:\git\mylocalgitspace\e-learning\PROCEDURES\PRINT_HELLO.sql
@D:\git\mylocalgitspace\e-learning\SYNONYMS\CATALOG.sql
@D:\git\mylocalgitspace\e-learning\SYNONYMS\COL.sql
@D:\git\mylocalgitspace\e-learning\SYNONYMS\PRODUCT_USER_PROFILE.sql
@D:\git\mylocalgitspace\e-learning\SYNONYMS\PUBLICSYN.sql
@D:\git\mylocalgitspace\e-learning\SYNONYMS\SYSCATALOG.sql
@D:\git\mylocalgitspace\e-learning\SYNONYMS\SYSFILES.sql
@D:\git\mylocalgitspace\e-learning\SYNONYMS\TAB.sql
@D:\git\mylocalgitspace\e-learning\SYNONYMS\TABQUOTAS.sql
@D:\git\mylocalgitspace\e-learning\QUEUES\AQ__DEF__AQCALL_E.sql
@D:\git\mylocalgitspace\e-learning\QUEUES\AQ__DEF__AQERROR_E.sql
@D:\git\mylocalgitspace\e-learning\QUEUES\DEF__AQCALL.sql
@D:\git\mylocalgitspace\e-learning\QUEUES\DEF__AQERROR.sql
@D:\git\mylocalgitspace\e-learning\QUEUE_TABLES\DEF__AQCALL.sql
@D:\git\mylocalgitspace\e-learning\QUEUE_TABLES\DEF__AQERROR.sql
