--------------------------------------------------------
--  DDL for Table MVIEW$_ADV_OUTPUT
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."MVIEW$_ADV_OUTPUT" 
   (	"RUNID#" NUMBER, 
	"OUTPUT_TYPE" NUMBER, 
	"RANK#" NUMBER, 
	"ACTION_TYPE" VARCHAR2(6), 
	"SUMMARY_OWNER" VARCHAR2(30), 
	"SUMMARY_NAME" VARCHAR2(30), 
	"GROUP_BY_COLUMNS" VARCHAR2(2000), 
	"WHERE_CLAUSE" VARCHAR2(2000), 
	"FROM_CLAUSE" VARCHAR2(2000), 
	"MEASURES_LIST" VARCHAR2(2000), 
	"FACT_TABLES" VARCHAR2(1000), 
	"GROUPING_LEVELS" VARCHAR2(2000), 
	"QUERYLEN" NUMBER, 
	"QUERY_TEXT" LONG, 
	"STORAGE_IN_BYTES" NUMBER, 
	"PCT_PERFORMANCE_GAIN" NUMBER, 
	"FREQUENCY" NUMBER, 
	"CUMULATIVE_BENEFIT" NUMBER, 
	"BENEFIT_TO_COST_RATIO" NUMBER, 
	"VALIDATED" NUMBER
   ) ;

   COMMENT ON TABLE "SYSTEM"."MVIEW$_ADV_OUTPUT"  IS 'Output table for summary recommendations and evaluations';
